#include <klvp/klvsselmtimpl.h>
// klvsslex generated on Thu Aug 15 09:15:01 2013

/////////////////////////////////////////////////////////////////////////////
// KLVUnknownSecurity
lcss::KLVUnknownSecurity::KLVUnknownSecurity(uint8_t key) { setKey(key); }
lcss::KLVUnknownSecurity::~KLVUnknownSecurity() {}
/////////////////////////////////////////////////////////////////////////////
//KLVObjectCountryCodingMethodVersionDate
lcss::KLVObjectCountryCodingMethodVersionDate::KLVObjectCountryCodingMethodVersionDate(){setKey(24);}
lcss::KLVObjectCountryCodingMethodVersionDate::~KLVObjectCountryCodingMethodVersionDate(){}
/////////////////////////////////////////////////////////////////////////////
//KLVSecurityClassification
lcss::KLVSecurityClassification::KLVSecurityClassification(){setKey(1);}
lcss::KLVSecurityClassification::~KLVSecurityClassification(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassifyingCountryandReleasingInstructionsCountryCodingMethod
lcss::KLVClassifyingCountryandReleasingInstructionsCountryCodingMethod::KLVClassifyingCountryandReleasingInstructionsCountryCodingMethod(){setKey(2);}
lcss::KLVClassifyingCountryandReleasingInstructionsCountryCodingMethod::~KLVClassifyingCountryandReleasingInstructionsCountryCodingMethod(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassifyingCountry
lcss::KLVClassifyingCountry::KLVClassifyingCountry(){setKey(3);}
lcss::KLVClassifyingCountry::~KLVClassifyingCountry(){}
/////////////////////////////////////////////////////////////////////////////
//KLVSecuritySCISHIinformation
lcss::KLVSecuritySCISHIinformation::KLVSecuritySCISHIinformation(){setKey(4);}
lcss::KLVSecuritySCISHIinformation::~KLVSecuritySCISHIinformation(){}
/////////////////////////////////////////////////////////////////////////////
//KLVCaveats
lcss::KLVCaveats::KLVCaveats(){setKey(5);}
lcss::KLVCaveats::~KLVCaveats(){}
/////////////////////////////////////////////////////////////////////////////
//KLVReleasingInstructions
lcss::KLVReleasingInstructions::KLVReleasingInstructions(){setKey(6);}
lcss::KLVReleasingInstructions::~KLVReleasingInstructions(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassifiedBy
lcss::KLVClassifiedBy::KLVClassifiedBy(){setKey(7);}
lcss::KLVClassifiedBy::~KLVClassifiedBy(){}
/////////////////////////////////////////////////////////////////////////////
//KLVDerivedFrom
lcss::KLVDerivedFrom::KLVDerivedFrom(){setKey(8);}
lcss::KLVDerivedFrom::~KLVDerivedFrom(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassificationReason
lcss::KLVClassificationReason::KLVClassificationReason(){setKey(9);}
lcss::KLVClassificationReason::~KLVClassificationReason(){}
/////////////////////////////////////////////////////////////////////////////
//KLVDeclassificationDate
lcss::KLVDeclassificationDate::KLVDeclassificationDate(){setKey(10);}
lcss::KLVDeclassificationDate::~KLVDeclassificationDate(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassificationandMarkingSystem
lcss::KLVClassificationandMarkingSystem::KLVClassificationandMarkingSystem(){setKey(11);}
lcss::KLVClassificationandMarkingSystem::~KLVClassificationandMarkingSystem(){}
/////////////////////////////////////////////////////////////////////////////
//KLVObjectCountryCodingMethod
lcss::KLVObjectCountryCodingMethod::KLVObjectCountryCodingMethod(){setKey(12);}
lcss::KLVObjectCountryCodingMethod::~KLVObjectCountryCodingMethod(){}
/////////////////////////////////////////////////////////////////////////////
//KLVObjectCountryCodes
lcss::KLVObjectCountryCodes::KLVObjectCountryCodes(){setKey(13);}
lcss::KLVObjectCountryCodes::~KLVObjectCountryCodes(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassificationComments
lcss::KLVClassificationComments::KLVClassificationComments(){setKey(14);}
lcss::KLVClassificationComments::~KLVClassificationComments(){}
/////////////////////////////////////////////////////////////////////////////
//KLVUMIDVideo
lcss::KLVUMIDVideo::KLVUMIDVideo(){setKey(15);}
lcss::KLVUMIDVideo::~KLVUMIDVideo(){}
/////////////////////////////////////////////////////////////////////////////
//KLVUMIDAudio
lcss::KLVUMIDAudio::KLVUMIDAudio(){setKey(16);}
lcss::KLVUMIDAudio::~KLVUMIDAudio(){}
/////////////////////////////////////////////////////////////////////////////
//KLVUMIDData
lcss::KLVUMIDData::KLVUMIDData(){setKey(17);}
lcss::KLVUMIDData::~KLVUMIDData(){}
/////////////////////////////////////////////////////////////////////////////
//KLVUMIDSystem
lcss::KLVUMIDSystem::KLVUMIDSystem(){setKey(18);}
lcss::KLVUMIDSystem::~KLVUMIDSystem(){}
/////////////////////////////////////////////////////////////////////////////
//KLVStreamID
lcss::KLVStreamID::KLVStreamID(){setKey(19);}
lcss::KLVStreamID::~KLVStreamID(){}
/////////////////////////////////////////////////////////////////////////////
//KLVTransportStreamID
lcss::KLVTransportStreamID::KLVTransportStreamID(){setKey(20);}
lcss::KLVTransportStreamID::~KLVTransportStreamID(){}
/////////////////////////////////////////////////////////////////////////////
//KLVItemDesignator
lcss::KLVItemDesignator::KLVItemDesignator(){setKey(21);}
lcss::KLVItemDesignator::~KLVItemDesignator(){}
/////////////////////////////////////////////////////////////////////////////
//KLVVersion
lcss::KLVVersion::KLVVersion(){setKey(22);}
lcss::KLVVersion::~KLVVersion(){}
/////////////////////////////////////////////////////////////////////////////
//KLVClassifyingCountryandReleasingInstructionsCountryCodingMethodVersionDate
lcss::KLVClassifyingCountryandReleasingInstructionsCountryCodingMethodVersionDate::KLVClassifyingCountryandReleasingInstructionsCountryCodingMethodVersionDate(){setKey(23);}
lcss::KLVClassifyingCountryandReleasingInstructionsCountryCodingMethodVersionDate::~KLVClassifyingCountryandReleasingInstructionsCountryCodingMethodVersionDate(){}

lcss::KLVSecurityElement::KLVSecurityElement()
{
}

lcss::KLVSecurityElement::~KLVSecurityElement()
{
}
